### ISSUE TITLE
Add `header--fixed` class

### ISSUE THREAD

**Issue by brettlangdon** [underdogio/underdog-styles#23]
This is mostly to appease `joinfetch` which currently has a fixed header which stays with you as you scroll the page.

This could be helpful for other sites, so adding `header--fixed` class should be easy/small enough change to make.

Styles from `joinfetch`:

``` css
.navbar--fixed {
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    z-index: 1000;
    height: 68px;
}
```
